{% set name = "conda-forge-metadata" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-forge-metadata/archive/refs/tags/{{ version }}.zip
  sha256: ac3cb2aafd1e21ffc5fcc48b709debe7a0b4fd3b2ae983c39f4ecc38363d57d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm >=7
  run:
    - python >={{ python_min }}
    - requests
    - ruamel.yaml
    - conda-oci-mirror
    - typing-extensions
    - conda-package-streaming
    - deprecated
    - beautifulsoup4

test:
  imports:
    - conda_forge_metadata
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/conda-forge/conda-forge-metadata
  summary: programatic access to conda-forge's metadata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
