{% set name = "conda-forge-metadata" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-forge-metadata/archive/refs/tags/{{ version }}.zip
  sha256: bf4a12338b5efbf4733cdcc5604badea1ba8d981329d13b783154a3c004b44fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools-scm >=7
  run:
    - python >=3.6
    - requests
    - ruamel.yaml
    - conda-oci-mirror
    - typing-extensions
    - conda-package-streaming
    - deprecated
    - beautifulsoup4

test:
  imports:
    - conda_forge_metadata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/conda-forge/conda-forge-metadata
  summary: programatic access to conda-forge's metadata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
