schema_version: 1

context:
  name: conda-forge-metadata
  version: "2026.9.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda-forge/conda-forge-metadata/archive/refs/tags/${{ version }}.tar.gz
  sha256: c5ef5e0f87c87df4006ede8a0c310e90013d4ee7b2cee60afada948483b84086

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm >=7
  run:
    - python >=${{ python_min }}
    - deprecated
    - requests
    - ruamel.yaml
    - typing-extensions
    - conda-oci-mirror
    - conda-package-streaming >=0.12.0

tests:
  - python:
      imports:
        - conda_forge_metadata
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: programatic access to conda-forge's metadata
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/conda-forge/conda-forge-metadata

extra:
  recipe-maintainers:
    - beckermr
